services:

  sensor-db:
    image: 'postgres:15.1-alpine'
    restart: always
    depends_on:
      - pgadmin
    environment:
      POSTGRES_DB: ${POSTGRES_SENSOR_DB}
      POSTGRES_USER: ${POSTGRES_SENSOR_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_SENSOR_PASSWORD}
    volumes:
      - ./db-data/sensor-service:/var/lib/postgresql/data
    networks:
      - monitor-sensors

  user-db:
    image: 'postgres:15.1-alpine'
    restart: always
    depends_on:
      - pgadmin
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_DURATION: ${JWT_ACCESS_DURATION}
      JWT_REFRESH_DURATION: ${JWT_REFRESH_DURATION}
    volumes:
      - ./db-data/user-service:/var/lib/postgresql/data
    networks:
      - monitor-sensors

  pgadmin:
    build: pgadmin
    restart: always
    image: monitor-sensors_pgadmin:1.0.0
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - monitor-sensors

  sensor-service:
    build: sensor-service
    restart: always
    env_file:
      - .env
    depends_on:
      - sensor-db
    networks:
      - monitor-sensors

  user-service:
    build: user-service
    restart: always
    env_file:
      - .env
    depends_on:
      - user-db
    networks:
      - monitor-sensors

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8088:8080"
    environment:
      URLS: ${SWAGGER_URLS}
    networks:
      - monitor-sensors

  proxy:
    build: proxy
    depends_on:
      - user-service
      - sensor-service
    ports:
      - "80:80"
    networks:
      - monitor-sensors

volumes:
  db-data:

networks:
  monitor-sensors:
    name: monitor-sensors
    driver: bridge