version: "3.8"

services:

  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5432:5432"
    env_file:
      - example.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - monitor-sensors

  pgadmin:
    build: pgadmin
    image: 'dpage/pgadmin4'
    ports:
      - "81:80"
    env_file:
      - example.env
    networks:
      - monitor-sensors

volumes:
  db-data:

networks:
  monitor-sensors:
    name: monitor-sensors
    driver: bridge