server:
  port: 8080

spring:
  application:
    name: user-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST_USER}/${POSTGRES_USER_DB}
    username: ${POSTGRES_USER_USERNAME}
    password: ${POSTGRES_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
security:
  jwt:
    secret: ${JWT_SECRET}
    access-duration: ${JWT_ACCESS_DURATION}
    refresh-duration: ${JWT_REFRESH_DURATION}
swagger:
  url: ${SWAGGER_URL}